### ISSUE TITLE
No plugin exists with the handle "geomate".

### ISSUE THREAD

**Issue by DandeSuen** [vaersaagod/geomate#28]
I have a problem, Output message ` No plugin exists with the handle "geomate".` at installing plugin geomate.
And the following is logs:
`2020-03-10 23:03:18 [-][14658][qqhpqgk2rlk8rce38eajjg2056][trace][yii\base\Controller::runAction] Route to run: plugins/install-plugin
2020-03-10 23:03:18 [-][14658][qqhpqgk2rlk8rce38eajjg2056][trace][yii\base\InlineAction::runWithParams] Running action: craft\controllers\PluginsController::actionInstallPlugin()
2020-03-10 23:03:18 [-][14658][qqhpqgk2rlk8rce38eajjg2056][info][yii\db\Command::query] SELECT `id`, `handle`, `version`, `schemaVersion`, `licenseKeyStatus`, `installDate`, `licensedEdition`
FROM `craft_plugins`
WHERE `handle`='geomate'
LIMIT 1
2020-03-10 23:03:18 [-][14658][qqhpqgk2rlk8rce38eajjg2056][profile begin][yii\db\Command::query] SELECT `id`, `handle`, `version`, `schemaVersion`, `licenseKeyStatus`, `installDate`, `licensedEdition`
FROM `craft_plugins`
WHERE `handle`='geomate'
LIMIT 1
2020-03-10 23:03:18 [-][14658][qqhpqgk2rlk8rce38eajjg2056][profile end][yii\db\Command::query] SELECT `id`, `handle`, `version`, `schemaVersion`, `licenseKeyStatus`, `installDate`, `licensedEdition`
FROM `craft_plugins`
WHERE `handle`='geomate'
LIMIT 1
2020-03-10 23:03:18 [-][14658][qqhpqgk2rlk8rce38eajjg2056][error][craft\errors\InvalidPluginException] craft\errors\InvalidPluginException: No plugin exists with the handle "geomate". in /data/stagingroot/craft3/vendor/craftcms/cms/src/services/Plugins.php:1380
Stack trace:
#0 /data/stagingroot/craft3/vendor/craftcms/cms/src/services/Plugins.php(819): craft\services\Plugins->_getPluginConfigData('geomate')
#1 /data/stagingroot/craft3/vendor/craftcms/cms/src/services/Plugins.php(469): craft\services\Plugins->getStoredPluginInfo('geomate')
#2 /data/stagingroot/craft3/vendor/craftcms/cms/src/controllers/PluginsController.php(50): craft\services\Plugins->installPlugin('geomate', NULL)
#3 [internal function]: craft\controllers\PluginsController->actionInstallPlugin()
#4 /data/stagingroot/craft3/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#5 /data/stagingroot/craft3/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#6 /data/stagingroot/craft3/vendor/craftcms/cms/src/web/Controller.php(178): yii\base\Controller->runAction('install-plugin', Array)
#7 /data/stagingroot/craft3/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('install-plugin', Array)
#8 /data/stagingroot/craft3/vendor/craftcms/cms/src/web/Application.php(291): yii\base\Module->runAction('plugins/install...', Array)
#9 /data/stagingroot/craft3/vendor/craftcms/cms/src/web/Application.php(559): craft\web\Application->runAction('plugins/install...', Array)
#10 /data/stagingroot/craft3/vendor/craftcms/cms/src/web/Application.php(270): craft\web\Application->_processActionRequest(Object(craft\web\Request))
#11 /data/stagingroot/craft3/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#12 /data/stagingroot/craft3/web/index.php(21): yii\base\Application->run()
#13 {main}
2020-03-10 23:03:18 [-][14658][qqhpqgk2rlk8rce38eajjg2056][trace][yii\base\View::renderFile] Rendering view file: /data/stagingroot/craft3/vendor/yiisoft/yii2/views/errorHandler/exception.php
2020-03-10 23:03:18 [-][14658][qqhpqgk2rlk8rce38eajjg2056][trace][yii\base\View::renderFile] Rendering view file: /data/stagingroot/craft3/vendor/yiisoft/yii2/views/errorHandler/callStackItem.php
2020-03-10 23:03:18 [-][14658][qqhpqgk2rlk8rce38eajjg2056][trace][yii\base\View::renderFile] Rendering view file: /data/stagingroot/craft3/vendor/yiisoft/yii2/views/errorHandler/callStackItem.php
2020-03-10 23:03:18 [-][14658][qqhpqgk2rlk8rce38eajjg2056][trace][yii\base\View::renderFile] Rendering view file: /data/stagingroot/craft3/vendor/yiisoft/yii2/views/errorHandler/callStackItem.php
2020-03-10 23:03:18 [-][14658][qqhpqgk2rlk8rce38eajjg2056][trace][yii\base\View::renderFile] Rendering view file: /data/stagingroot/craft3/vendor/yiisoft/yii2/views/errorHandler/callStackItem.php
2020-03-10 23:03:18 [-][14658][qqhpqgk2rlk8rce38eajjg2056][trace][yii\base\View::renderFile] Rendering view file: /data/stagingroot/craft3/vendor/yiisoft/yii2/views/errorHandler/callStackItem.php
2020-03-10 23:03:18 [-][14658][qqhpqgk2rlk8rce38eajjg2056][trace][yii\base\View::renderFile] Rendering view file: /data/stagingroot/craft3/vendor/yiisoft/yii2/views/errorHandler/callStackItem.php
2020-03-10 23:03:18 [-][14658][qqhpqgk2rlk8rce38eajjg2056][trace][yii\base\View::renderFile] Rendering view file: /data/stagingroot/craft3/vendor/yiisoft/yii2/views/errorHandler/callStackItem.php
2020-03-10 23:03:18 [-][14658][qqhpqgk2rlk8rce38eajjg2056][trace][yii\base\View::renderFile] Rendering view file: /data/stagingroot/craft3/vendor/yiisoft/yii2/views/errorHandler/callStackItem.php
2020-03-10 23:03:18 [-][14658][qqhpqgk2rlk8rce38eajjg2056][trace][yii\base\View::renderFile] Rendering view file: /data/stagingroot/craft3/vendor/yiisoft/yii2/views/errorHandler/callStackItem.php
2020-03-10 23:03:18 [-][14658][qqhpqgk2rlk8rce38eajjg2056][trace][yii\base\View::renderFile] Rendering view file: /data/stagingroot/craft3/vendor/yiisoft/yii2/views/errorHandler/callStackItem.php
2020-03-10 23:03:18 [-][14658][qqhpqgk2rlk8rce38eajjg2056][trace][yii\base\View::renderFile] Rendering view file: /data/stagingroot/craft3/vendor/yiisoft/yii2/views/errorHandler/callStackItem.php
2020-03-10 23:03:18 [-][14658][qqhpqgk2rlk8rce38eajjg2056][trace][yii\base\View::renderFile] Rendering view file: /data/stagingroot/craft3/vendor/yiisoft/yii2/views/errorHandler/callStackItem.php
2020-03-10 23:03:18 [-][14658][qqhpqgk2rlk8rce38eajjg2056][trace][yii\base\View::renderFile] Rendering view file: /data/stagingroot/craft3/vendor/yiisoft/yii2/views/errorHandler/callStackItem.php
2020-03-10 23:03:18 [-][14658][qqhpqgk2rlk8rce38eajjg2056][trace][yii\base\View::renderFile] Rendering view file: /data/stagingroot/craft3/vendor/yiisoft/yii2/views/errorHandler/callStackItem.php
2020-03-10 23:03:17 [-][14658][qqhpqgk2rlk8rce38eajjg2056][info][application] $_GET = [
    'p' => 'admin/settings/plugins'
]

**Comment by Odusanya** [comment]
Hey @DandeSuen did you install this plugin via composer alone?

**Comment by DandeSuen** [comment]
Sorry, I forget detail, But I have try `composer` and `/admin/utilities/updates` both. 
And this bug just happen at my test website. But my local website not have,

**Comment by DandeSuen** [comment]
After install `geomate` via composer, It's disable, Following is composer output.
`azureuser@prod:/data/stagingroot/craft3$ sudo composer require vaersaagod/geomate
Do not run Composer as root/super user! See https://getcomposer.org/root for details
Using version ^1.2 for vaersaagod/geomate
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 3 installs, 0 updates, 0 removals
  - Installing zonuexe/http-accept-language (0.4.1): Downloading (100%)         
  - Installing jaybizzle/crawler-detect (v1.2.94): Downloading (100%)         
  - Installing vaersaagod/geomate (v1.2.1): Downloading (100%)         
Package aelvan/imager is abandoned, you should avoid using it. Use spacecatninja/imager-x instead.
Writing lock file
Generating optimized autoload files
azureuser@prod:/data/stagingroot/craft3$ sudo ./craft install/plugin geomate
*** installing geomate
*** failed to install geomate: No plugin exists with the handle "geomate".

azureuser@prod:/data/stagingroot/craft3$ sudo ./craft install/plugin vaersaagod/geomate
*** installing vaersaagod/geomate
*** failed to install vaersaagod/geomate: No plugin exists with the handle "vaersaagod/geomate".
`

**Comment by aelvan** [comment]
This issue pops up from time to time, it's usually an issue with the local env, or project config. Have a look here: https://craftcms.stackexchange.com/questions/29739/invalid-plugin-no-plugin-exists-with-the-handle-craft-3

**Comment by DandeSuen** [comment]
I found the status of all plugins could not be disable or enable. It's not just geomate. 
I tried remove plugin,And delete any about geomate data from tables craft_plugins, craft_projectconfig. But the issue still here.

**Comment by DandeSuen** [comment]
Hey Everyone,

Thanks for you help.
Sorry, This BUG not is the geomate issue, It's two website using one Memcached caused by the issue.

Thanks again.
